package Member;

import java.io.Serializable;

/**
 * 새 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NewTableMember implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private String id;

	/** 패스워드. */
	private String password;

	/** 전화번호. */
	private String hp;

	/** 이메일. */
	private String email;

	/** 주소. */
	private String address;

	/** 사진. */
	private String pic;

	/**
	 * 생성자.
	 */
	public NewTableMember() {
	}

	/**
	 * id을 설정합니다..
	 * 
	 * @param id
	 *            id
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * id을 가져옵니다..
	 * 
	 * @return id
	 */
	public String getId() {
		return this.id;
	}

	/**
	 * 패스워드을 설정합니다..
	 * 
	 * @param password
	 *            패스워드
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * 패스워드을 가져옵니다..
	 * 
	 * @return 패스워드
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * 전화번호을 설정합니다..
	 * 
	 * @param hp
	 *            전화번호
	 */
	public void setHp(String hp) {
		this.hp = hp;
	}

	/**
	 * 전화번호을 가져옵니다..
	 * 
	 * @return 전화번호
	 */
	public String getHp() {
		return this.hp;
	}

	/**
	 * 이메일을 설정합니다..
	 * 
	 * @param email
	 *            이메일
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * 이메일을 가져옵니다..
	 * 
	 * @return 이메일
	 */
	public String getEmail() {
		return this.email;
	}

	/**
	 * 주소을 설정합니다..
	 * 
	 * @param address
	 *            주소
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * 주소을 가져옵니다..
	 * 
	 * @return 주소
	 */
	public String getAddress() {
		return this.address;
	}

	/**
	 * 사진을 설정합니다..
	 * 
	 * @param pic
	 *            사진
	 */
	public void setPic(String pic) {
		this.pic = pic;
	}

	/**
	 * 사진을 가져옵니다..
	 * 
	 * @return 사진
	 */
	public String getPic() {
		return this.pic;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		NewTableMember other = (NewTableMember) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
